import Foundation

extension Sites {
    enum Blacklist: String, CaseIterable {
        case
        pubmatic = "ads.pubmatic.com",
        dianomi = "www.dianomi.com",
        hotjar = "vars.hotjar.com",
        media = "contextual.media.net",
        googleapis = "imasdk.googleapis.com",
        twitter = "platform.twitter.com",
        adalliance = "mafo.adalliance.io",
        yieldlab = "ad.yieldlab.net",
        emsservice = "static.emsservice.de",
        flashtalking = "cdn.flashtalking.com",
        criteo = "gum.criteo.com",
        adition = "imagesrv.adition.com",
        openx = "us-u.openx.net",
        google_pagead = "www.google.com/pagead/",
        google_recaptcha = "www.google.com/recaptcha/",
        guim = "interactive.guim.co.uk",
        spiegel = "interactive.spiegel.de",
        indexww = "js-sec.indexww.com",
        the_ozone_project = "elb.the-ozone-project.com",
        googleadservices = "www.googleadservices.com",
        addthis = "s7.addthis.com",
        sparwelt = "widgets.sparwelt.click",
        adrtx = "adstax-match.adrtx.net",
        amazon_adsystem = "aax-eu.amazon-adsystem.com",
        dwcdn = "datawrapper.dwcdn.net",
        rubiconproject_assets = "secure-assets.rubiconproject.com",
        rubiconproject_eus = "eus.rubiconproject.com",
        creativecdn = "ams.creativecdn.com",
        youtube_embed = "www.youtube.com/embed",
        medtargetsystem = "www.medtargetsystem.com",
        snapchat = "tr.snapchat.com",
        linkedin = "platform.linkedin.com",
        google_analytics = "www.google-analytics.com",
        google_accounts = "accounts.google.com",
        ufpcdn = "ufpcdn.com",
        onclickgenius = "onclickgenius.com",
        appsflyer = "app.appsflyer.com",
        onmarshtompor = "onmarshtompor.com",
        rakamu = "rakamu.com",
        bongacams = "bongacams.com",
        bngpt = "bngpt.com",
        user_shield = "user-shield.com",
        adsco = "c.adsco.re",
        bet365 = "www.bet365.com",
        caradstag = "caradstag.casa",
        monkposseacre = "monkposseacre.casa",
        fgfgnbmeieorr910 = "fgfgnbmeieorr910.com",
        dexpredict = "www.dexpredict.com",
        hornsgrid = "hornsgrid.com",
        zap = "zap.buzz",
        google_consent = "consent.google.com",
        apostropheemailcompetence = "apostropheemailcompetence.com",
        googlesyndication = "googlesyndication.com",
        doubleclick = "doubleclick.net",
        cloudfront = "cloudfront.net"
    }
}
