import Foundation

extension Site {
    enum Domain: String, CaseIterable {
        case
        pubmatic = "pubmatic.com",
        dianomi = "dianomi.com",
        hotjar = "hotjar.com",
        media = "media.net",
        googleapis = "googleapis.com",
        twitter_platform = "platform.twitter.com",
        adalliance = "adalliance.io",
        yieldlab = "yieldlab.net",
        emsservice = "emsservice.de",
        flashtalking = "flashtalking.com",
        criteo = "criteo.com",
        adition = "adition.com",
        openx = "openx.net",
        guim = "guim.co.uk",
        spiegel = "interactive.spiegel.de",
        indexww = "indexww.com",
        the_ozone_project = "the-ozone-project.com",
        googleadservices = "googleadservices.com",
        addthis = "addthis.com",
        sparwelt = "sparwelt.click",
        adrtx = "adrtx.net",
        amazon_adsystem = "amazon-adsystem.com",
        dwcdn = "dwcdn.net",
        rubiconproject = "rubiconproject.com",
        creativecdn = "creativecdn.com",
        medtargetsystem = "medtargetsystem.com",
        snapchat = "tr.snapchat.com",
        linkedin = "platform.linkedin.com",
        google_analytics = "google-analytics.com",
        google_accounts = "accounts.google.com",
        ufpcdn = "ufpcdn.com",
        onclickgenius = "onclickgenius.com",
        appsflyer = "appsflyer.com",
        onmarshtompor = "onmarshtompor.com",
        rakamu = "rakamu.com",
        bongacams = "bongacams.com",
        bngpt = "bngpt.com",
        user_shield = "user-shield.com",
        adsco = "adsco.re",
        bet365 = "bet365.com",
        caradstag = "caradstag.casa",
        monkposseacre = "monkposseacre.casa",
        fgfgnbmeieorr910 = "fgfgnbmeieorr910.com",
        dexpredict = "dexpredict.com",
        hornsgrid = "hornsgrid.com",
        zap = "zap.buzz",
        google_consent = "consent.google.com",
        apostropheemailcompetence = "apostropheemailcompetence.com",
        googlesyndication = "googlesyndication.com",
        doubleclick = "doubleclick.net",
        cloudfront = "cloudfront.net",
        adnxs = "adnxs.com"
    }
}
