import Foundation

extension URL {
    enum Black: String, Website {
        case
        pubmatic,
        dianomi,
        hotjar,
        media,
        googleapis,
        adalliance,
        yieldlab,
        emsservice,
        flashtalking,
        criteo,
        adition,
        openx,
        indexww,
        googleadservices,
        addthis,
        sparwelt,
        adrtx,
        dwcdn,
        rubiconproject,
        creativecdn,
        medtargetsystem,
        ufpcdn,
        onclickgenius,
        appsflyer,
        onmarshtompor,
        rakamu,
        bongacams,
        bngpt,
        adsco,
        bet365,
        caradstag,
        monkposseacre,
        fgfgnbmeieorr910,
        dexpredict,
        hornsgrid,
        zap,
        apostropheemailcompetence,
        googlesyndication,
        doubleclick,
        cloudfront,
        adnxs,
        tinypass,
        lijit,
        piano,
        moatads,
        redditmedia,
        user_shield = "user-shield",
        google_analytics = "google-analytics",
        amazon_adsystem = "amazon-adsystem",
        the_ozone_project = "the-ozone-project",
        guim = "guim.co"
    }
}
