import Foundation

extension URL {
    enum Black: String, CaseIterable {
        case
        pubmatic,
        dianomi,
        hotjar,
        media,
        googleapis,
        adalliance,
        yieldlab,
        emsservice,
        flashtalking,
        criteo,
        adition,
        openx,
        indexww,
        googleadservices,
        addthis,
        sparwelt,
        adrtx,
        dwcdn,
        rubiconproject,
        creativecdn,
        medtargetsystem,
        ufpcdn,
        onclickgenius,
        appsflyer,
        onmarshtompor,
        rakamu,
        bongacams,
        bngpt,
        adsco,
        bet365,
        caradstag,
        monkposseacre,
        fgfgnbmeieorr910,
        dexpredict,
        hornsgrid,
        zap,
        apostropheemailcompetence,
        googlesyndication,
        doubleclick,
        cloudfront,
        adnxs,
        tinypass,
        lijit,
        piano,
        moatads,
        redditmedia,
        crwdcntrl,
        casalemedia,
        demdex,
        googletagservices,
        optimizely,
        cedexis,
        scorecardresearch,
        bounceexchange,
        zeusadx,
        adxnexus,
        revrtb,
        acertb,
        popmonetizer,
        tiodmw,
        ratappe,
        riverhit,
        ahojer,
        impactserving,
        f853150605ccb,
        reactivebetting,
        edigitalsurvey,
        concert,
        voxmedia,
        imrworldwide,
        getpublica,
        taboola,
        cedexis_radar = "cedexis-radar",
        user_shield = "user-shield",
        google_analytics = "google-analytics",
        amazon_adsystem = "amazon-adsystem",
        the_ozone_project = "the-ozone-project"
    }
}
